// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[lang]" | "/[lang]/about" | "/[lang]/about/denisse-martinez" | "/[lang]/admin/command" | "/[lang]/assessment" | "/[lang]/contact" | "/[lang]/insights" | "/[lang]/insights/[slug]" | "/[lang]/locations/[city]" | "/[lang]/locations/[city]/[service]" | "/[lang]/locations/[city]/industries/[industry]" | "/[lang]/locations/tijuana/master-guide" | "/[lang]/market-pulse" | "/[lang]/privacy" | "/[lang]/resources" | "/[lang]/resources/brochure" | "/[lang]/resources/questionnaire" | "/[lang]/resources/tijuana-industrial-park-map" | "/[lang]/services/call-center-tijuana" | "/[lang]/services/contract-manufacturing-tijuana" | "/[lang]/services/distribution-centers-tijuana" | "/[lang]/services/distribution-centers-tijuana/section-321-guide" | "/[lang]/services/industrial-real-estate-baja" | "/[lang]/services/nearshore-marketing" | "/[lang]/terms" | "/[lang]/tools/cost-calculator" | "/[lang]/tools/industrial-park-map" | "/admin" | "/admin/content-queue" | "/admin/crm" | "/admin/leads" | "/admin/marketing" | "/admin/posts" | "/admin/posts/[id]" | "/admin/posts/new" | "/admin/settings" | "/admin/sign-in/[[...sign-in]]" | "/campaigns/[slug]" | "/dashboard/prospecting"
type AppRouteHandlerRoutes = "/api/admin/ai/generate-ideas" | "/api/admin/ai/research-lead" | "/api/admin/ai/smart-reply" | "/api/admin/crm/campaigns" | "/api/admin/crm/campaigns/send" | "/api/admin/crm/senders" | "/api/admin/crm/upload" | "/api/admin/leads" | "/api/admin/metrics" | "/api/admin/posts" | "/api/admin/posts/[id]" | "/api/admin/stats" | "/api/agents/prospecting" | "/api/chat" | "/api/contact" | "/api/cron/campaign" | "/api/inngest" | "/api/lead-magnet" | "/api/posts" | "/api/posts/[slug]" | "/api/webhooks/brevo" | "/llms.txt"
type PageRoutes = never
type LayoutRoutes = "/" | "/[lang]" | "/[lang]/contact" | "/[lang]/insights/[slug]" | "/admin"
type RedirectRoutes = "/[lang]/discovery" | "/[lang]/locations/[city]/soft-landing-services" | "/company/name" | "/contact-accuracy-questionnaire" | "/discovery" | "/location/[slug]" | "/location/entry-node/third-pary-logistics-services" | "/location/marketing-assets" | "/location/questionnaire/product-service-needs" | "/locations/[city]/soft-landing-services"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[lang]": { "lang": string; }
  "/[lang]/about": { "lang": string; }
  "/[lang]/about/denisse-martinez": { "lang": string; }
  "/[lang]/admin/command": { "lang": string; }
  "/[lang]/assessment": { "lang": string; }
  "/[lang]/contact": { "lang": string; }
  "/[lang]/discovery": { "lang": string; }
  "/[lang]/insights": { "lang": string; }
  "/[lang]/insights/[slug]": { "lang": string; "slug": string; }
  "/[lang]/locations/[city]": { "lang": string; "city": string; }
  "/[lang]/locations/[city]/[service]": { "lang": string; "city": string; "service": string; }
  "/[lang]/locations/[city]/industries/[industry]": { "lang": string; "city": string; "industry": string; }
  "/[lang]/locations/[city]/soft-landing-services": { "lang": string; "city": string; }
  "/[lang]/locations/tijuana/master-guide": { "lang": string; }
  "/[lang]/market-pulse": { "lang": string; }
  "/[lang]/privacy": { "lang": string; }
  "/[lang]/resources": { "lang": string; }
  "/[lang]/resources/brochure": { "lang": string; }
  "/[lang]/resources/questionnaire": { "lang": string; }
  "/[lang]/resources/tijuana-industrial-park-map": { "lang": string; }
  "/[lang]/services/call-center-tijuana": { "lang": string; }
  "/[lang]/services/contract-manufacturing-tijuana": { "lang": string; }
  "/[lang]/services/distribution-centers-tijuana": { "lang": string; }
  "/[lang]/services/distribution-centers-tijuana/section-321-guide": { "lang": string; }
  "/[lang]/services/industrial-real-estate-baja": { "lang": string; }
  "/[lang]/services/nearshore-marketing": { "lang": string; }
  "/[lang]/terms": { "lang": string; }
  "/[lang]/tools/cost-calculator": { "lang": string; }
  "/[lang]/tools/industrial-park-map": { "lang": string; }
  "/admin": {}
  "/admin/content-queue": {}
  "/admin/crm": {}
  "/admin/leads": {}
  "/admin/marketing": {}
  "/admin/posts": {}
  "/admin/posts/[id]": { "id": string; }
  "/admin/posts/new": {}
  "/admin/settings": {}
  "/admin/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/api/admin/ai/generate-ideas": {}
  "/api/admin/ai/research-lead": {}
  "/api/admin/ai/smart-reply": {}
  "/api/admin/crm/campaigns": {}
  "/api/admin/crm/campaigns/send": {}
  "/api/admin/crm/senders": {}
  "/api/admin/crm/upload": {}
  "/api/admin/leads": {}
  "/api/admin/metrics": {}
  "/api/admin/posts": {}
  "/api/admin/posts/[id]": { "id": string; }
  "/api/admin/stats": {}
  "/api/agents/prospecting": {}
  "/api/chat": {}
  "/api/contact": {}
  "/api/cron/campaign": {}
  "/api/inngest": {}
  "/api/lead-magnet": {}
  "/api/posts": {}
  "/api/posts/[slug]": { "slug": string; }
  "/api/webhooks/brevo": {}
  "/campaigns/[slug]": { "slug": string; }
  "/company/name": {}
  "/contact-accuracy-questionnaire": {}
  "/dashboard/prospecting": {}
  "/discovery": {}
  "/llms.txt": {}
  "/location/[slug]": { "slug": string; }
  "/location/entry-node/third-pary-logistics-services": {}
  "/location/marketing-assets": {}
  "/location/questionnaire/product-service-needs": {}
  "/locations/[city]/soft-landing-services": { "city": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[lang]": never
  "/[lang]/contact": never
  "/[lang]/insights/[slug]": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
