// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/[lang]/about/denisse-martinez/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/about/denisse-martinez">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/about/denisse-martinez/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/about">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/admin/command/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/admin/command">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/admin/command/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/assessment">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/contact">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/insights/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/insights/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/insights/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/insights">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/locations/[city]/[service]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/locations/[city]/[service]">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/locations/[city]/[service]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/locations/[city]/industries/[industry]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/locations/[city]/industries/[industry]">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/locations/[city]/industries/[industry]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/locations/[city]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/locations/[city]">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/locations/[city]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/locations/tijuana/master-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/locations/tijuana/master-guide">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/locations/tijuana/master-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/market-pulse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/market-pulse">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/market-pulse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/privacy">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/resources/brochure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/resources/brochure">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/resources/brochure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/resources">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/resources/questionnaire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/resources/questionnaire">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/resources/questionnaire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/resources/tijuana-industrial-park-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/resources/tijuana-industrial-park-map">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/resources/tijuana-industrial-park-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/services/call-center-tijuana/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/services/call-center-tijuana">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/services/call-center-tijuana/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/services/contract-manufacturing-tijuana/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/services/contract-manufacturing-tijuana">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/services/contract-manufacturing-tijuana/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/services/distribution-centers-tijuana/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/services/distribution-centers-tijuana">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/services/distribution-centers-tijuana/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/services/distribution-centers-tijuana/section-321-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/services/distribution-centers-tijuana/section-321-guide">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/services/distribution-centers-tijuana/section-321-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/services/industrial-real-estate-baja/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/services/industrial-real-estate-baja">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/services/industrial-real-estate-baja/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/services/nearshore-marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/services/nearshore-marketing">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/services/nearshore-marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/terms">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/tools/cost-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/tools/cost-calculator">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/tools/cost-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/tools/industrial-park-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/tools/industrial-park-map">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/tools/industrial-park-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/content-queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content-queue">> = Specific
  const handler = {} as typeof import("../../../app/admin/content-queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm">> = Specific
  const handler = {} as typeof import("../../../app/admin/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leads">> = Specific
  const handler = {} as typeof import("../../../app/admin/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marketing">> = Specific
  const handler = {} as typeof import("../../../app/admin/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/posts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/posts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/posts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts/new">> = Specific
  const handler = {} as typeof import("../../../app/admin/posts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts">> = Specific
  const handler = {} as typeof import("../../../app/admin/posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/sign-in/[[...sign-in]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sign-in/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../../app/admin/sign-in/[[...sign-in]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/campaigns/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/campaigns/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/prospecting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/prospecting">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/prospecting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/ai/generate-ideas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ai/generate-ideas">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/ai/generate-ideas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/ai/research-lead/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ai/research-lead">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/ai/research-lead/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/ai/smart-reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ai/smart-reply">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/ai/smart-reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/crm/campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/crm/campaigns">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/crm/campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/crm/campaigns/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/crm/campaigns/send">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/crm/campaigns/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/crm/senders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/crm/senders">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/crm/senders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/crm/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/crm/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/crm/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/leads">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/metrics">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/posts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/posts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/agents/prospecting/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/prospecting">> = Specific
  const handler = {} as typeof import("../../../app/api/agents/prospecting/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/campaign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/campaign">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/campaign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inngest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inngest">> = Specific
  const handler = {} as typeof import("../../../app/api/inngest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/lead-magnet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lead-magnet">> = Specific
  const handler = {} as typeof import("../../../app/api/lead-magnet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/posts/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/api/posts/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts">> = Specific
  const handler = {} as typeof import("../../../app/api/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhooks/brevo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/brevo">> = Specific
  const handler = {} as typeof import("../../../app/api/webhooks/brevo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/llms.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/llms.txt">> = Specific
  const handler = {} as typeof import("../../../app/llms.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/[lang]/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[lang]/contact">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/insights/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[lang]/insights/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/insights/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[lang]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[lang]">> = Specific
  const handler = {} as typeof import("../../../app/[lang]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
