"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Loader2, Sparkles, Save, Eye, EyeOff } from "lucide-react";
import Link from "next/link";
import { SeoSidebar } from "@/components/admin/SeoSidebar";

export default function NewPostPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [post, setPost] = useState({
    title: "",
    slug: "",
    excerpt: "",
    content: "",
    category: "General",
    tags: "",
    imageUrl: "",
    readTime: "5 min read",
    published: false, // Add published state
  });

  // AI State
  const [showAiModal, setShowAiModal] = useState(false);
  const [aiTopic, setAiTopic] = useState("");
  const [generating, setGenerating] = useState(false);
  const [generatedIdeas, setGeneratedIdeas] = useState<any[] | null>(null);

  const handleSave = async () => {
    if (!post.title || !post.slug) {
      alert("Title and Slug are required.");
      return;
    }

    setLoading(true);
    try {
      const res = await fetch("/api/admin/posts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
            ...post,
            tags: post.tags.split(",").map(t => t.trim()).filter(Boolean)
        }),
      });

      if (!res.ok) throw new Error("Failed to create post");

      router.push("/admin/posts");
    } catch (error) {
      alert("Error saving post");
    } finally {
      setLoading(false);
    }
  };

  const generateIdeas = async () => {
    setGenerating(true);
    try {
        const res = await fetch("/api/admin/ai/generate-ideas", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ topic: aiTopic, count: 3 }),
        });
        const data = await res.json();
        if (data.ideas) {
            setGeneratedIdeas(data.ideas);
        } else {
            alert("Failed to generate ideas");
        }
    } catch (e) {
        alert("AI Error");
    } finally {
        setGenerating(false);
    }
  };

  const applyIdea = (idea: any) => {
    setPost({
        ...post,
        title: idea.title,
        excerpt: idea.excerpt,
        slug: idea.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)+/g, ""),
        content: `## ${idea.title}\n\n${idea.excerpt}\n\n(Generated by AI. Expand on this...)`
    });
    setGeneratedIdeas(null);
    setShowAiModal(false);
  };

  return (
    <div className="flex gap-8 items-start">
      {/* Main Content */}
      <div className="flex-1 max-w-4xl">
        <div className="flex items-center justify-between mb-8">
            <div>
                <h1 className="text-3xl font-bold text-white mb-2">New Blog Post</h1>
                <p className="text-slate-400">Create compelling content for your audience</p>
            </div>
            <div className="flex gap-3">
                <button
                    type="button"
                    onClick={() => setShowAiModal(true)}
                    className="px-4 py-2 bg-gradient-to-r from-purple-500 to-indigo-600 text-white rounded-lg hover:from-purple-600 hover:to-indigo-700 transition-all flex items-center gap-2 shadow-lg shadow-purple-500/20"
                >
                    <Sparkles className="w-4 h-4" />
                    AI Assistant
                </button>
                <button
                    onClick={() => router.push("/admin/posts")}
                    className="px-4 py-2 bg-slate-800 text-slate-300 rounded-lg hover:bg-slate-700 transition-colors"
                >
                    Cancel
                </button>
                <button
                    onClick={handleSave}
                    disabled={loading}
                    className="px-6 py-2 bg-gradient-to-r from-emerald-500 to-teal-500 text-white rounded-lg hover:from-emerald-600 hover:to-teal-600 transition-all shadow-lg shadow-emerald-500/20 font-medium flex items-center gap-2"
                >
                    {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : "Publish Post"}
                </button>
            </div>
        </div>

        <div className="glass-card p-8 space-y-8">
            {/* Title */}
            <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">Title</label>
                <input
                    type="text"
                    value={post.title}
                    onChange={(e) => setPost({ ...post, title: e.target.value })}
                    className="w-full bg-slate-900/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500/50 outline-none transition-all placeholder:text-slate-600 text-lg"
                    placeholder="Enter a catchy title..."
                />
            </div>

            <div className="grid grid-cols-2 gap-6">
                {/* Slug */}
                <div>
                    <label className="block text-sm font-medium text-slate-300 mb-2">Slug</label>
                    <input
                        type="text"
                        value={post.slug}
                        onChange={(e) => setPost({ ...post, slug: e.target.value })}
                        className="w-full bg-slate-900/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-emerald-500/50 outline-none font-mono text-sm"
                        placeholder="url-slug"
                    />
                </div>
                {/* Category */}
                <div>
                    <label className="block text-sm font-medium text-slate-300 mb-2">Category</label>
                    <select
                        value={post.category}
                        onChange={(e) => setPost({ ...post, category: e.target.value })}
                        className="w-full bg-slate-900/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-emerald-500/50 outline-none"
                    >
                        <option>General</option>
                        <option>Manufacturing</option>
                        <option>Logistics</option>
                        <option>Technology</option>
                    </select>
                </div>
            </div>

            {/* Excerpt */}
            <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">Excerpt (Meta Description)</label>
                <textarea
                    value={post.excerpt}
                    onChange={(e) => setPost({ ...post, excerpt: e.target.value })}
                    className="w-full bg-slate-900/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-emerald-500/50 outline-none transition-all resize-none h-24"
                    placeholder="Brief summary..."
                />
            </div>

            {/* Content */}
            <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">Content (Markdown)</label>
                <textarea
                    value={post.content}
                    onChange={(e) => setPost({ ...post, content: e.target.value })}
                    className="w-full bg-slate-900/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-emerald-500/50 outline-none transition-all font-mono leading-relaxed"
                    rows={20}
                    placeholder="# Hello World..."
                />
            </div>
        </div>
      </div>

      {/* SEO Sidebar */}
      <div className="w-80 shrink-0">
         <SeoSidebar title={post.title} excerpt={post.excerpt} content={post.content} slug={post.slug} />
      </div>

      {/* AI Modal */}
      {showAiModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in duration-300">
            <div className="glass-card w-full max-w-lg p-8 shadow-2xl scale-100 animate-in zoom-in-95 duration-300 border-white/10">
                <div className="flex items-center gap-3 mb-6">
                    <div className="p-3 bg-indigo-500/20 rounded-xl">
                        <Sparkles className="w-6 h-6 text-indigo-400" />
                    </div>
                    <div>
                        <h3 className="text-xl font-bold text-white">AI Blog Assistant</h3>
                        <p className="text-sm text-slate-400">Powered by Gemini Pro</p>
                    </div>
                </div>
                
                {!generatedIdeas ? (
                    <div className="space-y-4">
                        <div>
                            <label className="block text-sm font-medium text-slate-300 mb-2">Topic or Keyword</label>
                            <input 
                                type="text" 
                                className="w-full bg-slate-950/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-indigo-500/50 outline-none"
                                placeholder="e.g. Nearshoring trends in 2025"
                                value={aiTopic}
                                onChange={e => setAiTopic(e.target.value)}
                            />
                        </div>
                        <div className="flex gap-3 pt-2">
                            <button 
                                onClick={() => setShowAiModal(false)}
                                className="flex-1 px-4 py-3 bg-slate-800 text-slate-300 rounded-xl hover:bg-slate-700 transition-colors font-medium"
                            >
                                Cancel
                            </button>
                            <button 
                                onClick={generateIdeas}
                                disabled={generating || !aiTopic}
                                className="flex-1 px-4 py-3 bg-indigo-600 text-white rounded-xl hover:bg-indigo-700 transition-colors font-medium disabled:opacity-50 flex items-center justify-center gap-2"
                            >
                                {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : "Generate Ideas"}
                            </button>
                        </div>
                    </div>
                ) : (
                    <div className="space-y-4">
                        <p className="text-sm text-slate-400 mb-2">Select an idea to use:</p>
                        <div className="space-y-3 max-h-60 overflow-y-auto pr-2 custom-scrollbar">
                            {generatedIdeas.map((idea, idx) => (
                                <div 
                                    key={idx}
                                    onClick={() => applyIdea(idea)}
                                    className="p-4 bg-slate-800/50 hover:bg-indigo-500/20 border border-white/5 hover:border-indigo-500/30 rounded-xl cursor-pointer transition-all group"
                                >
                                    <h4 className="font-semibold text-white group-hover:text-indigo-300 mb-1">{idea.title}</h4>
                                    <p className="text-xs text-slate-400 line-clamp-2">{idea.excerpt}</p>
                                </div>
                            ))}
                        </div>
                        <button 
                            onClick={() => setGeneratedIdeas(null)}
                            className="w-full py-2 text-sm text-slate-500 hover:text-white transition-colors"
                        >
                            ← Back to Topic
                        </button>
                    </div>
                )}
            </div>
        </div>
      )}
    </div>
  );
}
