/**
 * AUTO-GENERATED BY MarketPulseAgent
 * DO NOT EDIT MANUALLY
 */

export interface MarketAlert {
    id: string;
    topic: string;
    date: string;
    impactLevel: "HIGH" | "MEDIUM" | "LOW";
    affectedSectors: string[];
    affectedCities: string[];
    summary: string;
}

export const MARKET_ALERTS: MarketAlert[] = [
    {
        "id": "usmca-2026-compliance",
        "topic": "USMCA 2026 Audit Requirements",
        "date": "March 19, 2026",
        "impactLevel": "HIGH",
        "affectedSectors": [
            "automotive",
            "medical-devices"
        ],
        "affectedCities": [
            "tijuana",
            "monterrey",
            "juarez"
        ],
        "summary": "New USMCA labor audits require 48-hour compliance response windows for IMMEX plants. Non-compliance could trigger immediate tariff 'reversions' to Most Favored Nation (MFN) rates."
    },
    {
        "id": "energy-surcharge-baja",
        "topic": "Grid Surcharge in Northern Mexico",
        "date": "March 18, 2026",
        "impactLevel": "MEDIUM",
        "affectedSectors": [
            "electronics"
        ],
        "affectedCities": [
            "mexicali",
            "reynosa"
        ],
        "summary": "Baja California industrial grid surcharge announced for peak summer hours (June-Aug). High-volume electronics assembly plants are advised to shift heavy production to off-peak night shifts."
    }
];
