/**
 * AUTO-GENERATED BY MarketPulseAgent (Live)
 * Generated: 2026-05-25T20:16:27.502Z
 * Source: Tavily real-time search
 * DO NOT EDIT MANUALLY — re-run: npx tsx scripts/agents/market_pulse_agent.ts
 */

export interface MarketAlert {
  id: string;
  topic: string;
  date: string;
  impactLevel: "HIGH" | "MEDIUM" | "LOW";
  affectedSectors: string[];
  affectedCities: string[];
  summary: string;
}

export const MARKET_ALERTS: MarketAlert[] = [
  {
    "id": "usmca-trade-policy-update",
    "topic": "USMCA Trade Policy Update",
    "date": "May 25, 2026",
    "impactLevel": "HIGH",
    "affectedSectors": [
      "automotive",
      "medical-devices",
      "electronics"
    ],
    "affectedCities": [
      "tijuana",
      "monterrey",
      "juarez",
      "matamoros"
    ],
    "summary": "The USMCA review in 2026 resets origin rules, tightens China content limits, and new tariffs affect Mexico manufacturing. Mexico faces new tariffs on strategic products. Tariff volatility drives nearshoring to Mexico."
  },
  {
    "id": "mexico-labor-cost-update",
    "topic": "Mexico Labor Cost Update",
    "date": "May 25, 2026",
    "impactLevel": "LOW",
    "affectedSectors": [
      "manufacturing",
      "electronics",
      "automotive"
    ],
    "affectedCities": [
      "tijuana",
      "mexicali",
      "juarez",
      "monterrey"
    ],
    "summary": "The 2026 daily minimum wage in Mexico is MXN $315.04 in the General Zone and MXN $440.87 in the Northern Border Free Zone. Manufacturing labor costs range from $5.56 to $47.67 per hour, fully burdened. These rates took effect on January 1, 2026."
  },
  {
    "id": "baja-california-industrial-market",
    "topic": "Baja California Industrial Market",
    "date": "May 25, 2026",
    "impactLevel": "MEDIUM",
    "affectedSectors": [
      "industrial-real-estate",
      "logistics"
    ],
    "affectedCities": [
      "tijuana",
      "mexicali"
    ],
    "summary": "Baja California continues to attract significant nearshoring investment in 2026, with new industrial projects and infrastructure developments. The region's strong logistics and skilled labor force drive this growth. UBIQ³ Santa Fe Industrial Park's US$90M investment highlights the area's expanding industrial capacity."
  },
  {
    "id": "mexico-energy-grid-update",
    "topic": "Mexico Energy Grid Update",
    "date": "May 25, 2026",
    "impactLevel": "MEDIUM",
    "affectedSectors": [
      "electronics",
      "automotive",
      "heavy-manufacturing"
    ],
    "affectedCities": [
      "mexicali",
      "monterrey",
      "reynosa",
      "juarez"
    ],
    "summary": "The CFE industrial surcharge in Mexico for 2026 is part of the National Electric System Development Program, with a focus on expanding capacity and transitioning to renewable energy. The government announced an investment of MXN 624.6 billion for this purpose. The new regulatory framework for the electricity sector was enacted in March 2025."
  },
  {
    "id": "nearshoring-demand-surge",
    "topic": "Nearshoring Demand Surge",
    "date": "May 25, 2026",
    "impactLevel": "HIGH",
    "affectedSectors": [
      "contract-manufacturing",
      "shelter-services"
    ],
    "affectedCities": [
      "tijuana",
      "hermosillo",
      "monterrey",
      "saltillo"
    ],
    "summary": "Nearshoring to Mexico is a growing trend in 2026, driven by USMCA benefits and reduced tariffs. Mexico's FDI ranking has risen, reflecting increased investor interest. Companies are shifting production closer to North America to optimize supply chains."
  }
];
