/**
 * AUTO-GENERATED BY MarketPulseAgent (Live)
 * Generated: 2026-05-20T00:00:00.000Z
 * Source: WebSearch real-time intelligence
 * DO NOT EDIT MANUALLY — re-run: npx tsx scripts/agents/market_pulse_agent.ts
 */

export interface MarketAlert {
  id: string;
  topic: string;
  date: string;
  impactLevel: "HIGH" | "MEDIUM" | "LOW";
  affectedSectors: string[];
  affectedCities: string[];
  summary: string;
}

export const MARKET_ALERTS: MarketAlert[] = [
  {
    "id": "usmca-trade-policy-update",
    "topic": "USMCA Trade Policy Update",
    "date": "May 20, 2026",
    "impactLevel": "HIGH",
    "affectedSectors": [
      "automotive",
      "medical-devices",
      "electronics"
    ],
    "affectedCities": [
      "tijuana",
      "monterrey",
      "juarez",
      "matamoros"
    ],
    "summary": "On May 7, 2026, the U.S. Court of International Trade ruled the 10% Section 122 tariffs on Mexican imports invalid, creating fresh legal uncertainty ahead of the July 1 USMCA joint review. Bilateral discussions launched March 5, 2026 are focused on tightening automotive rules-of-origin (currently 75% RVC) and limiting Chinese-content in USMCA-qualifying goods. USMCA utilization surged from ~45% in early 2025 to nearly 89% by late 2025. USMCA-qualifying goods remain exempt under all tariff regimes. Mexico countered with new tariffs of 10–50% on 1,463 tariff lines, though U.S./Canada USMCA imports are unaffected. The July 1 review is the single most consequential trade policy event on the 2026 nearshoring calendar."
  },
  {
    "id": "mexico-labor-cost-update",
    "topic": "Mexico Labor Cost Update",
    "date": "May 20, 2026",
    "impactLevel": "HIGH",
    "affectedSectors": [
      "manufacturing",
      "electronics",
      "automotive"
    ],
    "affectedCities": [
      "tijuana",
      "mexicali",
      "juarez",
      "monterrey"
    ],
    "summary": "Mexico's 2026 minimum wage stands at MXN $315.04/day (general zone) and MXN $440.87/day in the Northern Border Free Zone (+5% from 2025). The constitutional reform enacted March 3, 2026 reduces the standard workweek from 48 to 40 hours, increasing effective labor costs for manufacturers. Fully burdened hourly cost for a production operator is now $5.00–$6.50 USD (including IMSS, INFONAVIT, SAR, ISN, and statutory benefits) — still 60–75% below equivalent U.S. roles. Annual wage growth is running 8–12% at entry level. Border cities run 30–75% above interior rates due to the NBFZ premium. The 40-hour workweek reform is the most significant compliance change for 2026 planning."
  },
  {
    "id": "baja-california-industrial-market",
    "topic": "Baja California Industrial Market",
    "date": "May 20, 2026",
    "impactLevel": "HIGH",
    "affectedSectors": [
      "industrial-real-estate",
      "logistics",
      "aerospace"
    ],
    "affectedCities": [
      "tijuana",
      "mexicali"
    ],
    "summary": "Industrial vacancy in Baja California is below 1%, with Tijuana lease rates at approximately $0.50/sq ft — reflecting extreme supply tightness. New industrial facility construction takes roughly two years, creating a structural bottleneck for companies seeking rapid capacity expansion. Tijuana and Mexicali host Mexico's largest aerospace cluster (100+ companies) and continue attracting automotive, medical device, and electronics manufacturers. Nationwide industrial park investment accelerated in 2025–2026 with new parks planned across Baja California, Chihuahua, Nuevo León, and Jalisco. For site selectors, the key constraint is now available space and utilities, not demand."
  },
  {
    "id": "mexico-energy-grid-update",
    "topic": "Mexico Energy Grid Update",
    "date": "May 20, 2026",
    "impactLevel": "MEDIUM",
    "affectedSectors": [
      "electronics",
      "automotive",
      "heavy-manufacturing"
    ],
    "affectedCities": [
      "mexicali",
      "monterrey",
      "reynosa",
      "juarez"
    ],
    "summary": "CFE is executing an $8.2 billion transmission expansion plan specifically targeting manufacturing corridors in northern Mexico, with a 2026–2027 portfolio of 58 infrastructure projects. Average industrial electricity cost is $0.117–$0.119/kWh under the GDMTH tariff (high-demand manufacturing), comparable to Illinois and Tennessee and 12–30% below Michigan, Ontario, or New York. The GDMTH tariff uses time-of-use pricing: peak hours (6–10 PM winter, 8–10 PM summer) carry the highest rates, while off-peak rates run 30–40% below peak. CFE is initiating construction of 6 GW of new generation capacity in 2026. Private renewable energy procurement contracts face ongoing regulatory uncertainty under the 2025 energy reform."
  },
  {
    "id": "nearshoring-demand-surge",
    "topic": "Nearshoring Demand Surge",
    "date": "May 20, 2026",
    "impactLevel": "HIGH",
    "affectedSectors": [
      "contract-manufacturing",
      "shelter-services",
      "logistics"
    ],
    "affectedCities": [
      "tijuana",
      "hermosillo",
      "monterrey",
      "saltillo"
    ],
    "summary": "Mexico climbed from 25th to 19th in Kearney's 2026 FDI Confidence Index and ranks 7th globally in FDI flows, attracting a record $40.87 billion in 2025 (+10.8% YoY). 2026 FDI is projected at $40–45 billion. The binding constraint on nearshoring growth has shifted from demand to supply: industrial vacancy below 1% in key border markets, water demand projected to exceed supply by 30% by 2030, and energy grid capacity in manufacturing corridors under strain. Decisions are increasingly risk-adjusted — companies are prioritizing execution certainty and infrastructure availability over pure cost arbitrage. Automotive, medical devices, and electronics remain the leading sectors."
  }
];
