import sitemap from '../app/sitemap';
import { getLocation } from '../app/constants/seo-data';
import { getAllPosts, getPostBySlug } from '../app/constants/blog-data';
import { INDEXABLE_LOCALES, TIER1_CITIES } from '../app/constants/seo-config';

async function main() {
  console.log('=== VERIFYING GSC NOINDEX FIX ===\n');

  // 1. Generate Sitemap
  const routes = sitemap();
  console.log(`Total URLs generated by sitemap(): ${routes.length}`);

  // 2. Check for any noindex blog URLs (zh/ko)
  const zhKoBlogUrls = routes.filter(r => 
    r.url.includes('/zh/insights/') || r.url.includes('/ko/insights/')
  );
  console.log(`\nChinese/Korean blog URLs in sitemap: ${zhKoBlogUrls.length}`);
  if (zhKoBlogUrls.length > 0) {
    console.error('FAIL: Found zh/ko blog URLs in sitemap:', zhKoBlogUrls.map(r => r.url));
    process.exit(1);
  } else {
    console.log('PASS: 0 zh/ko blog URLs in sitemap.');
  }

  // 3. Check for any deprecated locale URLs in sitemap
  const deprecatedUrls = routes.filter(r => 
    r.url.includes('/fr/') || r.url.includes('/it/') || r.url.includes('/pt/') || r.url.includes('/ru/')
  );
  console.log(`\nDeprecated locale URLs in sitemap: ${deprecatedUrls.length}`);
  if (deprecatedUrls.length > 0) {
    console.error('FAIL: Found deprecated locale URLs in sitemap:', deprecatedUrls.map(r => r.url));
    process.exit(1);
  } else {
    console.log('PASS: 0 deprecated locale URLs in sitemap.');
  }

  // 4. Check Chihuahua City indexability
  const chihLocation = getLocation('chihuahua-city');
  if (!chihLocation) {
    console.error('FAIL: Chihuahua City location not found!');
    process.exit(1);
  }
  const hasSubstantialContent = !!(chihLocation.howItWorksSection || (chihLocation.serviceHowItWorks && Object.keys(chihLocation.serviceHowItWorks).length > 0));
  console.log(`\nChihuahua City hasSubstantialContent: ${hasSubstantialContent}`);
  if (!hasSubstantialContent) {
    console.error('FAIL: Chihuahua City lacks substantial content! It will emit noindex!');
    process.exit(1);
  } else {
    console.log('PASS: Chihuahua City has substantial content and will be 100% indexable.');
  }

  // 5. Check all blog posts indexability in indexable locales
  const posts = getAllPosts();
  console.log(`\nTotal blog posts: ${posts.length}`);
  const BLOG_INDEXABLE_LANGS = new Set(INDEXABLE_LOCALES);
  
  let noindexBlogCount = 0;
  INDEXABLE_LOCALES.forEach(lang => {
    posts.forEach(post => {
      const isIndexable = BLOG_INDEXABLE_LANGS.has(lang);
      if (!isIndexable) {
        noindexBlogCount++;
      }
    });
  });
  console.log(`Blog posts with noindex across INDEXABLE_LOCALES: ${noindexBlogCount}`);
  if (noindexBlogCount > 0) {
    console.error('FAIL: Blog posts returned noindex for an indexable locale!');
    process.exit(1);
  } else {
    console.log('PASS: 0 blog posts return noindex for any indexable locale.');
  }

  // 6. Check hreflang consistency across all sitemap entries
  let inconsistentAlternates = 0;
  routes.forEach(r => {
    if (!r.alternates?.languages) {
      inconsistentAlternates++;
    }
  });
  console.log(`\nSitemap entries missing alternates.languages: ${inconsistentAlternates}`);
  if (inconsistentAlternates > 0) {
    console.error('FAIL: Some sitemap entries missing alternates!');
    process.exit(1);
  } else {
    console.log('PASS: 100% of sitemap entries have proper alternates.languages.');
  }

  console.log('\n========================================');
  console.log('ALL VERIFICATION CHECKS PASSED PERFECTLY!');
  console.log('========================================');
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
