/**
 * market_pulse_agent.ts
 *
 * PHASE 2: Autonomous Market Reaction — LIVE VERSION
 * Monitors global trade news (USMCA, Tariffs, Labor Laws, nearshoring trends),
 * analyzes impact on specific industrial hubs, and publishes real alerts.
 *
 * Run: npx tsx scripts/agents/market_pulse_agent.ts
 */

import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';
import { tavily } from '@tavily/core';

const envPath = path.join(process.cwd(), '.env.local');
dotenv.config({ path: envPath });

interface MarketAlert {
  id: string;
  topic: string;
  date: string;
  impactLevel: 'HIGH' | 'MEDIUM' | 'LOW';
  affectedSectors: string[];
  affectedCities: string[];
  summary: string;
}

const SEARCH_QUERIES = [
  {
    query: 'USMCA nearshoring Mexico manufacturing 2026 tariff update',
    topic: 'USMCA Trade Policy Update',
    sectors: ['automotive', 'medical-devices', 'electronics'],
    cities: ['tijuana', 'monterrey', 'juarez', 'matamoros'],
  },
  {
    query: 'Mexico manufacturing labor cost minimum wage 2026',
    topic: 'Mexico Labor Cost Update',
    sectors: ['manufacturing', 'electronics', 'automotive'],
    cities: ['tijuana', 'mexicali', 'juarez', 'monterrey'],
  },
  {
    query: 'Baja California industrial real estate nearshoring investment 2026',
    topic: 'Baja California Industrial Market',
    sectors: ['industrial-real-estate', 'logistics'],
    cities: ['tijuana', 'mexicali'],
  },
  {
    query: 'Mexico energy electricity CFE industrial surcharge 2026',
    topic: 'Mexico Energy Grid Update',
    sectors: ['electronics', 'automotive', 'heavy-manufacturing'],
    cities: ['mexicali', 'monterrey', 'reynosa', 'juarez'],
  },
  {
    query: 'nearshoring Mexico US supply chain reshoring 2026 trend',
    topic: 'Nearshoring Demand Surge',
    sectors: ['contract-manufacturing', 'shelter-services'],
    cities: ['tijuana', 'hermosillo', 'monterrey', 'saltillo'],
  },
];

function classifyImpact(content: string): 'HIGH' | 'MEDIUM' | 'LOW' {
  const highKeywords = ['tariff', 'ban', 'suspended', 'executive order', 'emergency', 'critical', 'surge', 'record', 'crisis'];
  const mediumKeywords = ['increase', 'change', 'update', 'new', 'announced', 'expected', 'projected'];
  const lower = content.toLowerCase();
  if (highKeywords.some(k => lower.includes(k))) return 'HIGH';
  if (mediumKeywords.some(k => lower.includes(k))) return 'MEDIUM';
  return 'LOW';
}

function generateId(topic: string): string {
  return topic.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

async function main() {
  console.log('\n📡 [MarketPulseAgent] Initializing live data collection...');

  const apiKey = process.env.TAVILY_API_KEY;
  if (!apiKey) {
    console.error('❌ TAVILY_API_KEY not set in .env.local. Cannot run live agent.');
    console.log('💡 Falling back to keeping existing market-pulse-news.ts unchanged.');
    process.exit(0);
  }

  const client = tavily({ apiKey });
  const alerts: MarketAlert[] = [];
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  for (const q of SEARCH_QUERIES) {
    try {
      console.log(`🔍 Searching: "${q.query}"...`);
      const result = await client.search(q.query, {
        search_depth: 'basic',
        max_results: 3,
        include_answer: true,
      });

      // Build summary from top results
      const snippets = result.results
        ?.slice(0, 2)
        .map(r => r.content?.slice(0, 400))
        .filter(Boolean)
        .join(' ') || '';

      const summary = result.answer
        ? result.answer.slice(0, 500)
        : snippets.slice(0, 500) || 'No summary available.';

      if (summary.length > 50) {
        alerts.push({
          id: generateId(q.topic),
          topic: q.topic,
          date: today,
          impactLevel: classifyImpact(summary),
          affectedSectors: q.sectors,
          affectedCities: q.cities,
          summary: summary.replace(/"/g, "'").trim(),
        });
        console.log(`  ✅ Alert created: ${q.topic} [${classifyImpact(summary)}]`);
      } else {
        console.log(`  ⚠️  Skipping (insufficient content): ${q.topic}`);
      }

      // Rate limit: 1 request per 2 seconds for free tier
      await new Promise(resolve => setTimeout(resolve, 2000));
    } catch (err) {
      console.error(`  ❌ Failed to fetch "${q.topic}":`, err);
    }
  }

  if (alerts.length === 0) {
    console.log('\n⚠️  No alerts generated. Keeping existing market-pulse-news.ts unchanged.');
    process.exit(0);
  }

  // Generate the TypeScript file
  const fileContent = `/**
 * AUTO-GENERATED BY MarketPulseAgent (Live)
 * Generated: ${new Date().toISOString()}
 * Source: Tavily real-time search
 * DO NOT EDIT MANUALLY — re-run: npx tsx scripts/agents/market_pulse_agent.ts
 */

export interface MarketAlert {
  id: string;
  topic: string;
  date: string;
  impactLevel: "HIGH" | "MEDIUM" | "LOW";
  affectedSectors: string[];
  affectedCities: string[];
  summary: string;
}

export const MARKET_ALERTS: MarketAlert[] = ${JSON.stringify(alerts, null, 2)};
`;

  const outputPath = path.join(process.cwd(), 'app/constants/market-pulse-news.ts');
  fs.writeFileSync(outputPath, fileContent, 'utf8');

  console.log(`\n✅ [MarketPulseAgent] Published ${alerts.length} live alerts to: ${outputPath}`);
  console.log('✅ Cycle Complete.\n');
}

main().catch(err => {
  console.error('[MarketPulseAgent] Fatal error:', err);
  process.exit(1);
});
